set -e
true
true
/jet/home/wisenbac/Student-Led-Tutorial-2-Abby/SPAdes-3.15.0-Linux/bin/spades-hammer /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/corrected/configs/config.info
/usr/bin/python3 /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/SPAdes-3.15.0-Linux/share/spades/spades_pipeline/scripts/compress_all.py --input_file /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/corrected/corrected.yaml --ext_python_modules_home /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/SPAdes-3.15.0-Linux/share/spades --max_threads 16 --output_dir /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/corrected --gzip_output
true
true
/jet/home/wisenbac/Student-Led-Tutorial-2-Abby/SPAdes-3.15.0-Linux/bin/spades-core /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K21/configs/config.info
/jet/home/wisenbac/Student-Led-Tutorial-2-Abby/SPAdes-3.15.0-Linux/bin/spades-core /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K33/configs/config.info
/jet/home/wisenbac/Student-Led-Tutorial-2-Abby/SPAdes-3.15.0-Linux/bin/spades-core /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K55/configs/config.info
/jet/home/wisenbac/Student-Led-Tutorial-2-Abby/SPAdes-3.15.0-Linux/bin/spades-core /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/configs/config.info
/usr/bin/python3 /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/SPAdes-3.15.0-Linux/share/spades/spades_pipeline/scripts/copy_files.py /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/before_rr.fasta /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/before_rr.fasta /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/assembly_graph_after_simplification.gfa /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/assembly_graph_after_simplification.gfa /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/final_contigs.fasta /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/contigs.fasta /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/first_pe_contigs.fasta /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/first_pe_contigs.fasta /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/strain_graph.gfa /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/strain_graph.gfa /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/scaffolds.fasta /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/scaffolds.fasta /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/scaffolds.paths /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/scaffolds.paths /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/assembly_graph_with_scaffolds.gfa /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/assembly_graph_with_scaffolds.gfa /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/assembly_graph.fastg /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/assembly_graph.fastg /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/K77/final_contigs.paths /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/contigs.paths
true
/usr/bin/python3 /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/SPAdes-3.15.0-Linux/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/scaffolds.fasta --misc_dir /jet/home/wisenbac/Student-Led-Tutorial-2-Abby/spades_output/misc --threshold_for_breaking_scaffolds 3
true
